DROP TABLE IF EXISTS WorkoutSession;
CREATE TABLE WorkoutSession(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, workoutSessionDate INTEGER);
DROP TABLE IF EXISTS ExerciseSession;
CREATE TABLE ExerciseSession(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, exerciseId INTEGER, workoutSessionId INTEGER);
DROP TABLE IF EXISTS Exercise;
CREATE TABLE Exercise(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR, muscleGroup INTEGER);
DROP TABLE IF EXISTS WeightSet;
CREATE TABLE WeightSet(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, weight INTEGER, reps INTEGER, exerciseSessionId INTEGER);