DROP TABLE IF EXISTS WorkoutSession;
CREATE TABLE WorkoutSession(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, workoutSessionDate int);
DROP TABLE IF EXISTS ExerciseSession;
CREATE TABLE ExerciseSession(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, exerciseId long, workoutSessionId int);
DROP TABLE IF EXISTS Exercise;
CREATE TABLE Exercise(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR, muscleGroup int);
DROP TABLE IF EXISTS WeightSet;
CREATE TABLE WeightSet(_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, weight int, reps int, exerciseSessionId int);